help/DIAGRAM.md, migrations/Version20250402141131.php, public/docs/components/responses/user/CommonDefinitions.yaml, public/docs/components/schemas/inscription-event.yaml, public/docs/components/schemas/user.yaml, src/DataFixtures/Entity/UserFixtures.php, src/Entity/User.php, src/Enum/UserStatusEnum.php, tests/Fixtures/UserTestFixtures.php, tests/Functional/Api/UserApiControllerTest.php, tests/Unit/Entity/UserEntityTest.php
| Branch?       | feat/add-status-in-user-entity                                                |
| Issues        | Fix #30   |
=> Adds status attribute in user entity

assets/styles/components/navbar.css, config/environment/aurora.regmel.yaml, config/environment/aurora.yaml, cypress/e2e/web/_components/navbar.cy.js, templates/_components/navbar.html.twig
| Branch?       | feature/navbar-dynamic-config                                       |
| Bug fix?      | no                                                                                                            |
| New feature?  | yes                                                  |
| Deprecations? | no                                  |
| Issues        | Fix #29  |
Alterei a navbar para permitir sua modificação dinâmica por meio do arquivo de configuração. Além disso, neste PR, ajustei o componente …
=> Make navbar configurable via environment file

assets/js/user/edit-profile.js, config/routes/admin/user.yaml, src/Controller/Web/Admin/UserAdminController.php, src/DataFixtures/Entity/AgentFixtures.php, src/Entity/User.php, src/Regmel/Controller/Web/RegisterController.php, templates/_admin/user/_partials/edit-header.html.twig, templates/_admin/user/_partials/forms/agent-data.html.twig, templates/_admin/user/_partials/forms/entity-edit-form.html.twig, templates/_admin/user/_partials/forms/user-data.html.twig, templates/_admin/user/account-privacy.html.twig, templates/_admin/user/edit-profile.html.twig, tests/Functional/Api/AgentApiControllerTest.php, tests/Functional/Controller/Web/Admin/UserAdminWebControllerTest.php, tests/Unit/Entity/UserEntityTest.php, tests/Unit/Helper/PasswordHasherTest.php, translations/messages.en.yaml, translations/messages.es.yaml, translations/messages.pt-br.yaml, translations/messages.regmel.yaml
| Branch?       | feat/form-edit-user-profile                                               |
| Issues        | Fix #9   |
=> Adds form edit user profile

assets/styles/pages/admin-dashboard.css, config/environment/aurora.regmel.yaml, config/environment/aurora.yaml, cypress/e2e/admin/dashboard/home.cy.js, src/Controller/Web/Admin/DashboardAdminController.php, templates/_admin/dashboard/_partials/entity-cards.html.twig, templates/_admin/dashboard/_partials/recent-registrations.html.twig
| Branch?       | feature/dashboard-dynamic-config|
| Bug fix?      | no|
| Issues        | Fix #25  |
=> Make dashboard configurable via environment file

config/environment/aurora.regmel.yaml, config/environment/aurora.yaml, templates/_components/navbar.html.twig, translations/messages.regmel.yaml
| Branch?       |   feature/menu-dynamic-condig                               |
| Bug fix?      | no                                                                                                                |
| New feature?  | yes                                                 |
| Deprecations? | no                                        |
| Issues        | Fix #26  |
=> Make menu configurable via environment file

templates/_admin/user/account-privacy.html.twig, translations/messages.regmel.yaml
| Branch?       | improv/create-translation-account-privacy|
| Issues        | Fix #3   |
=> Create Translation of Account and Privacy

assets/js/user/edit-profile/image-validation.js, assets/js/user/edit-profile/load-agent-data.js, src/Controller/Web/Admin/UserAdminController.php, src/Service/AgentService.php, src/Service/FileService.php, src/Service/OpportunityService.php, src/Service/OrganizationService.php, src/Service/UserService.php, templates/_admin/user/_partials/edit-header.html.twig, templates/_admin/user/_partials/forms/agent-data.html.twig, templates/_admin/user/_partials/forms/entity-edit-form.html.twig, templates/_admin/user/_partials/forms/user-data.html.twig, templates/_admin/user/account-privacy.html.twig, templates/_admin/user/edit-profile.html.twig, translations/messages.regmel.yaml
| Branch?       | feat/image-user-form-update                                               |
| Issues        | Fix #50   |
=> Adds image edit in update user form.

src/Controller/Web/OrganizationWebController.php
| Branch?       |improv/list-municipalities-screen                                          |
| Issues        | Fix #72  |
=> List only "Municipality" on the municipalities screen.

assets/js/regmel/register.js, assets/styles/app.css, templates/regmel/register/_partials/organization-data.html.twig, templates/regmel/register/_partials/user-data.html.twig, templates/regmel/register/city.html.twig, translations/messages.pt-br.yaml, translations/messages.regmel.yaml
| Branch?       | improvement/user-municipality-register-form                                |
| Bug fix?      | yes                                                                                                              |
| New feature?  | no                                                                 |
| Deprecations? | no                                               |
| Issues        | Fix #44  |
=> Improvement user register form

assets/js/company/load-company-infos.js, src/DataFixtures/Entity/OrganizationFixtures.php, src/Regmel/Controller/Web/Admin/CompanyAdminController.php, templates/regmel/admin/company/_partials/modal-edit.html.twig, templates/regmel/admin/company/list.html.twig, translations/messages.regmel.yaml
| Branch?       | feat/create-modal-edit-company                                           |
| Issues        | Fix #53   |
=> Adds company edit form modal.

cypress/e2e/admin/user/user-list.cy.js, migrations/Version20250411192516.php, src/Controller/Web/Admin/UserAdminController.php, src/DataFixtures/Entity/UserFixtures.php, src/Entity/User.php, src/Enum/UserRolesEnum.php, src/Regmel/Command/CreateAdminUserCommand.php, src/Regmel/Command/CreateDemoForRegmelCommand.php, src/Regmel/Controller/Web/RegisterController.php, src/Security/Voter/AbstractVoter.php, src/Security/Voter/UserVoter.php, templates/_components/side-bar.html.twig, tests/Functional/Controller/Web/RegisterControllerTest.php
| Branch?       | 7.2 for features / 5.4, 6.4, 7.0, and 7.1 for bug fixes                                                 |
| Bug fix?      | yes/no                                                                                                                    |
| New feature?  | yes/no                                                                    |
| Deprecations? | yes/no                                                   |
| Issues        | Fix #49  |
=> Implement Voter and Roles

src/Regmel/Controller/Web/Admin/CompanyAdminController.php, src/Regmel/Controller/Web/Admin/MunicipalityAdminController.php, templates/regmel/admin/company/details.html.twig, templates/regmel/admin/company/timeline.html.twig, templates/regmel/admin/municipality/details.html.twig, templates/regmel/admin/municipality/timeline.html.twig
| Branch?       | feature/adds-timeline-for-municipality-company                                 |
| Bug fix?      | no                                                                                                        |
| New feature?  |yes                  |
| Deprecations? | no                     |
| Issues        | Fix #93  |
=> Adds timeline informations for municipality/company

config/environment/aurora.regmel.yaml, config/environment/aurora.yaml, cypress/e2e/web/space/space-list-filter.cy.js, src/Controller/Web/Admin/DashboardAdminController.php, src/Entity/User.php, src/Regmel/Controller/Web/RegisterController.php, src/Regmel/Service/RegisterService.php, src/Service/AbstractEntityService.php, templates/_admin/dashboard/_partials/entity-cards.html.twig, templates/_components/side-bar.html.twig
=> Config menu and dashboard using ACL from user

assets/js/regmel/register.js, config/packages/security.yaml, config/routes/api/user.yaml, src/Controller/Api/UserApiController.php
| Branch?       | feature/validate-email-availability                                        |
| Bug fix?      | no                                                                                                       |
| New feature?  | yes                              |
| Deprecations? | no                                   |
| Issues        | Fix #107  |
=> Validate email availability

src/Regmel/Service/RegisterService.php, src/Repository/Interface/UserRepositoryInterface.php, src/Repository/UserRepository.php, src/Service/AccountEventService.php, src/Service/InscriptionOpportunityService.php, src/Service/Interface/AccountEventServiceInterface.php, templates/_emails/notifications/manager/new-registration.html.twig, translations/messages.regmel.yaml
| Branch?       |feat/send-email-new-user-for-maneger                                               |
| Issues        | Fix #94   |
=> Send email notification to manager on organization registration.

src/Regmel/Controller/Web/Admin/MunicipalityAdminController.php, templates/regmel/admin/municipality/details.html.twig
| Branch?       | improvement/members-of-organizations                                             |
| Bug fix?      |no                                                                                                                 |
| New feature?  | no                                                           |
| Deprecations? |no                                |
| Issues        | Fix #121  |
Tomei a liberdade de mudar o ícone de membros
=> Improvement organziation's members page

help/DIAGRAM.md, help/ENUM.md, migrations/Version20250416230106.php, public/docs/components/responses/state/CommonDefinitions.yaml, public/docs/components/schemas/state.yaml, src/Entity/State.php, src/Enum/RegionEnum.php, tests/Unit/Entity/StateEntityTest.php
| Branch?       | feat/add-culumn-region-in-state                                               |
| Issues        | Fix #148   |
=> Adds column region in state table.

assets/styles/app.css, templates/_admin/dashboard/index.html.twig
| Branch?       |fix/sidebar                                              |
| Bug fix?      | yes         |
| New feature?  |no                                   |
| Deprecations? |no                                |
| Issues        | Fix #129  |
=> Fix sidebar

cypress/e2e/admin/architectural-accessibility/architectural-accessibility-list.cy.js, src/Regmel/Controller/Web/Admin/MunicipalityAdminController.php
| Branch?       |                      improv/avoid-deleting-the-form-when-editing-a-municipality                          |
| Issues        | Fix #149  |
=> Avoid deleting the form when editing a municipality.

src/Regmel/Controller/Web/Admin/CompanyAdminController.php, src/Regmel/Controller/Web/Admin/MunicipalityAdminController.php, src/Repository/OrganizationRepository.php, src/Service/OrganizationService.php, templates/regmel/admin/company/list.html.twig
| Branch?       | feat/adjust-the-filter-the-my-company-screen                                             |
| Issues        | Fix #83   |
=> Adjust the filter my company screen.

src/Regmel/Controller/Web/RegisterController.php, templates/regmel/admin/municipality/details.html.twig, templates/regmel/admin/municipality/documents.html.twig, templates/regmel/admin/municipality/list.html.twig
| Branch?       |improv/save-region-extrafields                                                |
| Issues        | Fix #164   |
=> Adds improvements to the extra fields of the municipality and the display of the municipality name.

templates/_admin/user/list.html.twig, translations/messages.regmel.yaml
| Branch?       | improv/report-user-status-the-list-screen                                                |
| Issues        | Fix #168   |
=> Report user status on the list screen.

assets/js/company/load-company-infos.js, assets/js/organization/load-organization-infos.js, templates/regmel/admin/company/_partials/modal-edit.html.twig, templates/regmel/admin/municipality/_partials/modal-edit.html.twig
| Branch?       | improv/modal-edit-company                                               |
| Issues        | Fix #157   |
=> Adds improvements in modal edit company.

src/Service/AccountEventService.php, src/Service/UserService.php, templates/_emails/account-event/password-reset-new-user.html.twig, translations/messages.regmel.yaml
| Branch?       | feat/edit-password-first-login                                                |
| Issues        | Fix #170   |
=> require new users to set a password when created by admin.

src/Document/InviteTimeline.php, src/Event/Invite/AcceptInviteEvent.php, src/Event/Invite/RemoveInviteEvent.php, src/Event/Invite/SendInviteEvent.php, src/EventListener/Audit/AuditInviteListener.php, src/Service/InviteService.php
| Branch?       | feature/create-invite-events |
| Issues        | Fix #163 |
=> Create invite events

src/Regmel/Controller/Web/Admin/MunicipalityAdminController.php, templates/regmel/admin/municipality/list.html.twig, translations/messages.regmel.yaml
| Branch?       | feat/add-filter-region-municipality                                              |
| Issues        | Fix #180   |
=> Adds region and state filter in munipality list page when role by adm or manager.

README.md, help/DEPLOY.md
=> Docs for deploy

translations/messages.regmel.yaml
| Branch?       |   improv/translate-updated-at-header                                     |
| Issues        | Fix #192  |
=> Translate updated_at header in municipality document.

assets/styles/app.css, assets/styles/colors.css, assets/styles/components/navbar.css, assets/styles/components/side-bar.css, templates/_admin/opportunity/_partials/details/phases.html.twig, templates/_admin/user/list.html.twig
| Branch?       |improv/change-primary-color-the-entire-project                                            |
| Issues        | Fix #179   |
=> Change the primary color of the entire project

cypress/aurora/e2e/admin/architectural-accessibility/architectural-accessibility-list.cy.js, cypress/regmel/e2e/web/company/company-register.cy.js, tests/Functional/Controller/Web/CompanyWebControllerTest.php
| Branch?       | test/ceate-e2e-tests-for-company-registration                                                |
| Issues        | Fix #134  |
=> Create E2E tests for Company registration.

src/Regmel/Controller/Web/Admin/CompanyAdminController.php, src/Regmel/Controller/Web/Admin/MunicipalityAdminController.php, templates/regmel/admin/company/_partials/forms/address-data.html.twig, templates/regmel/admin/company/_partials/forms/capacity-accessibility.html.twig, templates/regmel/admin/company/_partials/forms/entity-edit-form.html.twig, templates/regmel/admin/company/_partials/forms/introduction.html.twig, templates/regmel/admin/company/_partials/forms/opening-hours.html.twig, templates/regmel/admin/company/_partials/forms/permissions.html.twig, templates/regmel/admin/company/_partials/space-edit-header.html.twig, templates/regmel/admin/company/_partials/tabs/tabs.html.twig, templates/regmel/admin/company/add.html.twig, templates/regmel/admin/company/details.html.twig
=> Adjustments for proposals

templates/regmel/admin/company/_partials/modal-edit.html.twig, templates/regmel/admin/municipality/_partials/modal-edit.html.twig
| Branch?       | adjust/mask-phone-and-cnpj-edit-company                                               |
| Issues        | Fix #157   |
=> Adds adjustments in phone and cnpj fields.

Makefile, help/DEPLOY.md
| Branch?       | feature/config-process-deploy |
| Issues        | Fix #205 |
=> Config process to deploy

templates/regmel/admin/company/timeline.html.twig, templates/regmel/admin/municipality/timeline.html.twig
| Branch?       |adjust/remove-empty-column-in-timeline                                                |
| Issues        | Fix #191   |
=> Remove empty column in company and municipality timeline.

templates/_admin/user/list.html.twig, translations/messages.regmel.yaml
| Branch?       |   improv/show-user-roles-in-list-screen                                             |
| Issues        | Fix #200 |
=> Show User Roles in List Screen.

templates/regmel/admin/municipality/list.html.twig
| Branch?       | fix/show-state-selected                                                |
| Bug fix?      | yes                                                                                                                 |
| Issues        | Fix #196   |
=> Fix state filter dont show the state selected

assets/js/form-utils.js, templates/regmel/admin/municipality/_partials/list-filters.html.twig, templates/regmel/admin/municipality/list.html.twig
| Branch?       | feat/reset-municipality-filters                                                |
| New feature?  | yes                                                          |
| Issues        | Fix #14   |
=> Add button to reset municipality filters

assets/js/modal-confirm-documentation.js, src/Regmel/Controller/Web/Admin/MunicipalityDocumentAdminController.php, templates/regmel/admin/municipality/documents.html.twig
| Branch?       | feat/approve-doc-municipality                                             |
| New feature?  | yes                                                                  |
| Issues        | Fix #166   |
Como está:
=> Approve or refuse documents from municipality

src/Entity/Organization.php, src/Regmel/Controller/Web/Admin/MunicipalityAdminController.php, src/Service/OrganizationService.php, templates/regmel/admin/municipality/details.html.twig, translations/messages.regmel.yaml
| Branch?       | feature/implements-remove-member                                                |
| Bug fix?      | no                                                                                                              |
| Deprecations? | no                       |
| Issues        | Fix #162  |
=> Implements remove member from organization

src/Regmel/Controller/Web/InviteController.php
| Branch?       | fix/loggedout-user-cant-accept-invite                                                |
| Bug fix?      | yes                                                                                                                   |
| New feature?  | no                                                                   |
| Issues        | Fix #211   |
=> Fix logged out user cant accept invites

cypress/regmel/e2e/web/municipality/register.cy.js, src/Regmel/Controller/Web/RegisterController.php, src/Regmel/Service/RegisterService.php, src/Service/FileService.php, src/Service/Interface/FileServiceInterface.php
| Branch?       | improv/modify-join-term-default-name                                                |
| Issues        | Fix #237   |
Como está:
=> Modify join term standard name

translations/messages.regmel.yaml
| Branch?       | improv/translate-no-data-found-message                                         |
| Issues        | Fix #216 |
=> Translate no data found message

templates/_admin/user/list.html.twig
| Branch?       | improv/hide-profile-from-the-list-apply-different-color                                 |
| Issues        | Fix #219 |
=> Hide Standard User profile from the list and apply a different color.

assets/js/load-cities.js, assets/js/load-filters.js, assets/styles/app.css, cypress/regmel/e2e/web/municipality/register.cy.js, templates/regmel/admin/municipality/_partials/list-filters.html.twig, templates/regmel/admin/municipality/list.html.twig, templates/regmel/register/_partials/organization-data.html.twig
| Branch?       | improv/apply-tom-select-city-state-selects                                         |
| Issues        | Fix #215   |
=> Apply the tom-select lib the city and state selects.

Makefile, help/DEPLOY.md
| Branch?       | fix/permission-on-makefile |
| Deprecations? | yes |
| Issues        | Fix #205 |
=> Fix permissions on Makefile

config/environment/aurora.regmel.yaml, src/Regmel/Controller/Web/Admin/ProposalAdminController.php, templates/regmel/admin/proposal/list.html.twig
| Branch?       |feature/create-proposal-page                                        |
| Bug fix?      | no                                                                                                                |
| New feature?  | yes                                              |
| Deprecations? | no                                  |
| Issues        | Fix #225  |
=> Create proposal list page

src/Entity/Organization.php, templates/regmel/admin/company/_partials/modal-edit.html.twig, templates/regmel/admin/municipality/_partials/modal-edit.html.twig, tests/Unit/Entity/OrganizationTest.php
| Branch?       | adjust/new-fields-timeline-table                                             |
| Issues        | Fix #213  |
=> Adds new fields to timeline table.

src/Regmel/Controller/Web/Admin/MunicipalityDocumentAdminController.php, templates/regmel/admin/municipality/_partials/list-filters.html.twig, templates/regmel/admin/municipality/documents.html.twig, templates/regmel/admin/municipality/list.html.twig
| Branch?       |feat/add-filters-municipality-document                                              |
| Issues        | Fix #231   |
=> Adds filters in municipality document list page.

assets/js/load-filters.js, src/Regmel/Controller/Web/Admin/CompanyAdminController.php, src/Regmel/Controller/Web/Admin/MunicipalityAdminController.php, src/Repository/Interface/OrganizationRepositoryInterface.php, src/Repository/OrganizationRepository.php, src/Service/AbstractEntityService.php, src/Service/Interface/OrganizationServiceInterface.php, src/Service/OrganizationService.php, templates/regmel/admin/company/_partials/list-filters.html.twig, templates/regmel/admin/company/list.html.twig, translations/messages.regmel.yaml
| Branch?       | feat/button-export-company-list                                                |
| Bug fix?      | yes/no                                                                                                                    |
| New feature?  | yes/                                                                    |
| Issues        | Fix #228  Fix #251   |
- Região
- Estado
- Status do Documento
- Link para o documento …
=> Adds button for export company list .csv .

src/Regmel/Controller/Web/Admin/MunicipalityAdminController.php, src/Regmel/Controller/Web/RegisterController.php, src/Regmel/Service/Interface/RegisterServiceInterface.php, src/Regmel/Service/RegisterService.php, src/Service/AccountEventService.php, src/Service/Interface/AccountEventServiceInterface.php, templates/_emails/notifications/manager/new-municipality-document.html.twig, templates/regmel/admin/municipality/details.html.twig, translations/messages.regmel.yaml
| Branch?       | feature/allow-resend-municipality-document |
| Issues        | Fix #243 |
Demonstração do histórico dos termos.
Aqui está o documeto após ser reenviado.
Email enviado para notificar a SNP.
=> Allow resend municipality document

src/Regmel/Controller/Web/Admin/MunicipalityDocumentAdminController.php, src/Regmel/Service/Interface/MunicipalityDocumentServiceInterface.php, src/Regmel/Service/MunicipalityDocumentService.php, templates/regmel/admin/municipality/details.html.twig, templates/regmel/admin/municipality/documents.html.twig
| Branch?       | feature/accept-and-refuse-terms |
| Issues        | Fix #7 |
=> Accept and refuse terms

assets/js/modal-proposal-details.js, src/Regmel/Controller/Web/Admin/ProposalAdminController.php, src/Regmel/Service/ProposalService.php, src/Service/FileService.php, templates/regmel/_components/modal-proposal.html.twig, templates/regmel/admin/company/details.html.twig, templates/regmel/admin/proposal/_partials/forms/entity-edit-form.html.twig, templates/regmel/admin/proposal/list.html.twig
| Branch?       | feat/show-geographic-view-company-proposal                                             |
| New feature?  | yes                                                       |
| Issues        | Fix #226   |
=> Add modal to show company proposal files

src/Regmel/Controller/Web/Admin/ProposalAdminController.php, src/Regmel/Service/Interface/ProposalServiceInterface.php, src/Regmel/Service/ProposalService.php, templates/regmel/admin/proposal/list.html.twig, translations/messages.regmel.yaml, var/translations/index.d.ts, var/translations/index.js
| Branch?       | feat/export-proposal-project-files                                             |
| New feature?  | yes                                                   |
| Issues        | Fix #269   |
=> Export all Proposals project files

src/Regmel/Controller/Web/Admin/ProposalAdminController.php, src/Regmel/Service/Interface/ProposalServiceInterface.php, src/Regmel/Service/ProposalService.php, templates/regmel/admin/proposal/list.html.twig, translations/messages.regmel.yaml, var/translations/index.d.ts, var/translations/index.js
| Branch?       | feat/export-proposal-map-files                                               |
| New feature?  | yes                                                                   |
| Issues        | Fix #268  |
=> Download all poligonals files from proposals

assets/styles/app.css
| Branch?       | improv/centralize-the-document-approval                                          |
| Issues        | Fix #245   |
=> Centralize the document approval/rejection.

templates/regmel/_components/modal-proposal.html.twig, translations/messages.regmel.yaml
| Branch?       | improv/fix-field-label-for-number-of-households                                            |
| Issues        | Fix #276   |
=> fix field label for number of households

assets/js/modal-timeline.js, translations/messages.en.yaml, translations/messages.es.yaml, translations/messages.pt-br.yaml, translations/messages.regmel.yaml
| Branch?       | improv/translate-column-names-timeline-modal                                              |
| Issues        | Fix #159   |
=> Translate column names in timeline modal.

templates/_emails/notifications/manager/new-registration.html.twig
| Branch?       | improve/email-sent-to-snp |
| Issues        | Fix #282 |
=> Change email style sent to SNP

assets/styles/app.css, templates/regmel/admin/municipality/documents.html.twig
| Branch?       | fix/document-modal                    |
| Bug fix?      | yes                                                                                |
| New feature?  |no                                     |
| Deprecations? |no |
| Issues        | Fix #283  |
=> Fix document modal

templates/regmel/_components/modal-proposal.html.twig, translations/messages.regmel.yaml
| Branch?       | improv/change-archive-name                                              |
| Issues        | Fix #277 |
=> Change archives name.

src/Controller/Web/HomepageWebController.php, src/Regmel/Controller/Web/RegisterController.php, src/Repository/Interface/PhaseRepositoryInterface.php, src/Repository/PhaseRepository.php, src/Service/Interface/PhaseServiceInterface.php, src/Service/PhaseService.php, templates/homepage/not-logged.html.twig, templates/regmel/register/phase-not-active.html.twig, translations/messages.regmel.yaml
| Branch?       | feat/prevent-municipality-registration-deadline                                                |
| Issues        | Fix #16   |
=> Prevent municipality registration outside the accreditation period.

assets/styles/app.css
| Branch?       | improv/fix-user-photo-size                                            |
| Issues        | Fix #31   |
=> Fix user photo size.

templates/regmel/admin/company/details.html.twig, templates/regmel/admin/proposal/list.html.twig
| Branch?       | improvement/propsosal-status-color                                       |
| Bug fix?      | no                                                                                                        |
| New feature?  | no                                                            |
| Deprecations? |no                       |
| Issues        | Fix #12  |
=> Adds color to proposal status

assets/js/load-filters.js, src/Regmel/Controller/Web/Admin/MunicipalityDocumentAdminController.php, templates/regmel/_components/list-filters.html.twig, templates/regmel/admin/municipality/documents.html.twig, translations/messages.regmel.yaml
| Branch?       | feat/add-filter-document-status                                                |
| Issues        | Fix #6   |
=> Adds filter status in document list page.

assets/js/load-filters.js, src/Enum/StatusProposalEnum.php, src/Regmel/Controller/Web/Admin/ProposalAdminController.php, src/Repository/InitiativeRepository.php, src/Service/InitiativeService.php, templates/regmel/_components/list-filters.html.twig, templates/regmel/admin/proposal/list.html.twig, translations/messages.regmel.yaml
| Branch?       | feature/status-filter-proposal-page                                          |
| Bug fix?      |no                                                                                     |
| New feature?  | yes                                    |
| Deprecations? | no                 |
| Issues        | Fix #18  |
https://github.com/user-attachments/assets/346e6659-e22d-4ee3-9a80-65411ff7c7c2
=> Add status filter for proposal page

assets/js/regmel/register.js
| Branch?       | improv/validate-cpf                                              |
| Issues        | Fix #301  |
=> Only accept valid CPFs on forms

src/Controller/Web/HomepageWebController.php, src/Regmel/Controller/Web/RegisterController.php, src/Regmel/Service/Interface/RegisterServiceInterface.php, src/Regmel/Service/RegisterService.php, src/Repository/Interface/PhaseRepositoryInterface.php, src/Repository/PhaseRepository.php, templates/homepage/not-logged.html.twig
| Branch?       | feat/prevent-company-registration-after-deadline                                               |
| Bug fix?      |no                                                                                                                    |
| Issues        | Fix #260   |
=> Prevent company registration outside the accreditation period.

src/Regmel/Controller/Web/Admin/MunicipalityAdminController.php, src/Regmel/Service/Interface/MunicipalityServiceInterface.php, src/Regmel/Service/MunicipalityService.php, templates/regmel/admin/municipality/details.html.twig
| Branch?       | feature/municipality-details-proposals |
| Issues        | Fix #28 |
=> Add tab proposals in details of municipality

assets/styles/components/navbar.css, cypress/regmel/e2e/web/register/municipality-register.cy.js, templates/_admin/opportunity/list.html.twig, templates/_admin/user/list.html.twig, templates/regmel/admin/company/list.html.twig, templates/regmel/admin/municipality/documents.html.twig, templates/regmel/admin/municipality/list.html.twig
| Branch?       |improv/change-action-buttons-to-dropdown-menu-list                                              |
| Issues        | Fix #284  |
=> Change action buttons to dropdown menu list.

src/Regmel/Controller/Web/Admin/CompanyAdminController.php, src/Regmel/Controller/Web/Admin/ProposalAdminController.php, src/Service/InscriptionOpportunityService.php, src/Service/Interface/InscriptionOpportunityServiceInterface.php, src/Service/Interface/PhaseServiceInterface.php, src/Service/PhaseService.php, templates/homepage/not-logged.html.twig, templates/regmel/admin/company/_partials/modal-add-proposal-not-active.html.twig, templates/regmel/admin/company/details.html.twig, templates/regmel/admin/proposal/add-proposal-not-active.html.twig, translations/messages.regmel.yaml
| Branch?       | feat/prevent-send-proposal-after-deadline                                               |
| Issues        | Fix #318  |
- ####  O botão de "Nova Proposta" deve exibir um modal. Além disso, foi …
=> Prevent the submission of proposals outside the accreditation period.

cypress/regmel/e2e/web/register/municipality-register.cy.js, src/Regmel/Controller/Web/RegisterController.php, src/Service/OrganizationService.php, templates/regmel/admin/municipality/_partials/modal-edit.html.twig, templates/regmel/admin/municipality/details.html.twig, templates/regmel/register/_partials/organization-data.html.twig, translations/messages.regmel.yaml
| Branch?       | improv/add-fields-experience-housing-plan-the-municipality                                            |
| Issues        | Fix #307  |
=> Add experience & housing-plan fields to municipal registry.

src/Regmel/Service/ProposalService.php, translations/messages.regmel.yaml
| Branch?       |improvement/proposal-csv                    |
| Bug fix?      | yes                                                                                                                    |
| New feature?  | no                                                 |
| Deprecations? |no                                   |
| Issues        | Fix #316 |
=> Improvement proposal csv

src/Regmel/Service/ProposalService.php, translations/messages.regmel.yaml
| Branch?       | improv/fix-id-proposal-csv                                               |
| Deprecations? |no                                                   |
| Issues        | Fix #308   |
=> Improv proposal csv id.

cypress.config.js, cypress/regmel/e2e/web/proprosal/admin-proposal-list.cy.js
| Branch?       | feature/e2e-admin-proposal-details                                              |
| Bug fix?      | no                                                                                                           |
| New feature?  | yes                                |
| Deprecations? | no                                    |
| Issues        | Fix #256 |
```js
if (statusesElement) {
statusesElement.classList.remove('form-select');
new TomSelect(statusesElement, {
create: false,
placeholder: …
```
=> Create test e2e for proposal list page

assets/js/organization/load-organization-infos.js, src/Regmel/Controller/Web/Admin/MunicipalityAdminController.php, src/Service/OrganizationService.php, templates/regmel/admin/municipality/_partials/modal-edit.html.twig
| Branch?       | improv/fix-data-municipality-csv                                                |
| Issues        | Fix #309   |
=> Improv municipality csv data.

src/Service/OrganizationService.php
| Branch?       | improv/fix-data-company-csv                                               |
| Issues        | Fix #315   |
=> Modify company csv data

src/Regmel/Repository/Interface/MunicipalityRepositoryInterface.php, src/Regmel/Repository/MunicipalityRepository.php, src/Regmel/Service/Interface/MunicipalityServiceInterface.php, src/Regmel/Service/MunicipalityDocumentService.php, src/Regmel/Service/MunicipalityService.php, src/Regmel/Service/ProposalService.php, src/Regmel/Service/RegisterService.php, templates/regmel/admin/municipality/documents.html.twig
| Branch?       | feat/update-proposal-when-term-validated                                               |
| New feature?  | yes                                                                  |
| Issues        | Fix #327   |
=> Update proposals when municipalities terms are updated

src/DocumentService/OrganizationTimelineDocumentService.php, src/Regmel/Controller/Web/Admin/MunicipalityAdminController.php, src/Regmel/Service/Interface/ProposalServiceInterface.php, src/Regmel/Service/ProposalService.php, templates/_emails/new-proposal-status.html.twig, templates/regmel/admin/municipality/details.html.twig
| Branch?       | feature/agreement-proposals |
| Issues        | Fix #11 |
=> Create agreement of proposal

cypress/regmel/e2e/web/admin/download-terms.cy.js
| Branch?       | improv/create-e2e-tests-the-admin-export-documents-zip                                          |
| Issues        | Fix #255   |
=> Create E2E tests the admin export documents ZIP.

assets/js/modal-timeline.js, translations/messages.en.yaml, translations/messages.es.yaml, translations/messages.pt-br.yaml, translations/messages.regmel.yaml
| Branch?       | improv/translate-extra-fields-of-the-proposal-timeline-modal                                             |
| New feature?  | yes                                                                   |
| Issues        | Fix #343   |
=> Translate extra fields in the timeline modal of the proposals.

cypress.config.js, cypress/regmel/e2e/web/document/approve-and-recuse-document.cy.js, cypress/regmel/e2e/web/register/municipality-register.cy.js, cypress/regmel/e2e/web/register/register-companies-and-municipalities.cy.js, cypress/regmel/e2e/web/user/confirm-user.cy.js, cypress/regmel/support/commands.js, templates/regmel/register/_partials/organization-data.html.twig
| Branch?       | test/e2e-approve-or-recuse-document                                               |
| Issues        | Fix #322   |
=> test e2e approve and recuse document.

assets/js/regmel/modal-edit-phase.js, config/routes/admin/opportunity-phase.yaml, src/Controller/Web/Admin/OpportunityAdminController.php, src/Controller/Web/Admin/OpportunityPhaseAdminController.php, templates/_admin/opportunity/_partials/details/phases.html.twig, templates/_admin/opportunity/details.html.twig, translations/messages.en.yaml, translations/messages.es.yaml, translations/messages.pt-br.yaml, translations/messages.regmel.yaml
| Branch?       | feature/update-accreditation-phase                               |
| Bug fix?      | no                                                                                                           |
| New feature?  | yes                            |
| Deprecations? | no                                  |
| Issues        | Fix #75  |
https://github.com/user-attachments/assets/0bbcdfbc-d765-48eb-986b-9f28771ec604
=> Create modal to edit accreditation-phase

docker/nginx/default.conf
| Branch?       | fix/entity-too-large-error                                               |
| Bug fix?      | yes                                                                                                                    |
| Issues        | Fix #350   |
=> Fix nginx body too large error

assets/js/regmel/register.js, cypress/regmel/e2e/web/admin/company/invite-member-company.cy.js, cypress/regmel/e2e/web/register/company-register.cy.js, cypress/regmel/e2e/web/register/municipality-register.cy.js, cypress/regmel/e2e/web/register/register-companies-and-municipalities.cy.js, cypress/regmel/support/commands.js
| Branch?       | improvement/regiter-filter-order                                     |
| Bug fix?      | yes                                                                                                                   |
| New feature?  | no                                                 |
| Deprecations? | no                                               |
| Issues        | Fix #317  |
https://github.com/user-attachments/assets/4aeab733-02ef-4e3e-a9ef-05892107ca07
=> Improvement register filter order

templates/regmel/register/_partials/organization-data.html.twig, translations/messages.regmel.yaml
| Branch?       | improv/add-hint-to-two-related-municipality-fields                                            |
| New feature?  | yes                                                                   |
| Issues        | Fix #351   |
=> Add hint to two related municipality fields

translations/messages.regmel.yaml
| Branch?       | improv/fix-the-messag-in-the-accept-invitation-link                                          |
| Issues        | Fix #371   |
=> Fix the message in the accept invitation link.

cypress/regmel/e2e/web/admin/company/invite-member-company.cy.js, cypress/regmel/e2e/web/company/company-edit.cy.js, cypress/regmel/e2e/web/proprosal/proposal-add.cy.js, src/Regmel/Controller/Web/Admin/CompanyAdminController.php, templates/_components/side-bar.html.twig, templates/regmel/admin/company/details.html.twig
| Branch?       |feat/admin-hide-company-list                                               |
| Bug fix?      |no                                                                                                                    |
| Issues        | Fix #401   |
usuário membro de apenas 1 empresa:
usuário membro de mais de 1 empresa:
=> Hide company list/menu for single-company users and redirect to details page.

assets/js/organization/load-organization-infos.js, src/Regmel/Controller/Web/Admin/MunicipalityAdminController.php, src/Regmel/Controller/Web/RegisterController.php, templates/regmel/admin/municipality/_partials/modal-edit.html.twig, templates/regmel/admin/municipality/details.html.twig
| Branch?       | feat/edit-municipality-from-details-screen                                               |
| Bug fix?      | yes                                                                                                                  |
| New feature?  | yes                                                               |
| Issues        | Fix #402   |
=> Edit municipality from details page

cypress/tools/auto-register-companies.cy.js
| Branch?       | create-script-generate-fify-companies                                             |
| Deprecations? | yes                                                   |
| Issues        | Fix #392  |
=> Create script to generate fifty companies

cypress/regmel/e2e/web/admin/company/edit-company.cy.js
| Branch?       |test/validate-company-editing-the-company-listing-screen                                        |
| Issues        | Fix #386  |
=> Validate Company/OSC editing on the company listing screen.

cypress/regmel/e2e/web/user/confirm-user.cy.js, cypress/regmel/e2e/web/user/page-list.cy.js, templates/_admin/user/list.html.twig, templates/regmel/admin/company/details.html.twig
| Branch?       | improv/adjust-user-views-role-translation-and-confirmation                                         |
| Bug fix?      | no                                                                                                              |
| Issues        | Fix #328  |
=> Adjust user views role translation and confirmation button reorganization

cypress/regmel/e2e/web/document/resend-document.cy.js, templates/regmel/admin/municipality/details.html.twig
| Branch?       | feat/enable-template-download-resend-proposal                                                |
| New feature?  | yes                                                                   |
| Issues        | Fix #424 #425   |
Como está:
=> Enable template term download when resend term

assets/js/regmel/accept-polices.js, cypress/regmel/e2e/web/register/company-register.cy.js, cypress/regmel/e2e/web/register/municipality-register.cy.js, cypress/regmel/e2e/web/register/register-companies-and-municipalities.cy.js, templates/regmel/_components/modal-image-authorization.html.twig, templates/regmel/_components/modal-lgpd.html.twig, templates/regmel/_components/modal-privacy.html.twig, templates/regmel/register/_partials/accept-terms.html.twig, templates/regmel/register/city.html.twig, templates/regmel/register/company.html.twig
| Branch?       | feat/modal-of-terms-accession                                                |
| Deprecations? | yes                                                   |
| Issues        | Fix #426   |
obs: Identifiquei alguns problemas de usabilidade na abordagem que habilita o …
=> Adds a new way to accept policies.
